# Generated by Django 4.1.2 on 2023-01-24 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_user_token_request',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 0, 10, 55, 735022)),
        ),
    ]
