# Generated by Django 4.1.2 on 2023-01-24 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usersPortal', '0002_alter_user_last_user_token_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_user_token_request',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
