# Generated by Django 4.1.2 on 2023-01-27 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersPortal', '0003_alter_user_last_user_token_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_address',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='user_contactnumber',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='user_photo',
            options={'ordering': ['date_created']},
        ),
    ]
