# Generated by Django 4.1.2 on 2023-01-28 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersPortal', '0005_alter_user_address_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_address',
            unique_together={('address', 'location_of')},
        ),
    ]
