# Generated by Django 4.1.2 on 2023-02-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersPortal', '0006_alter_user_address_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_contactnumber',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_photo',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
