# Generated by Django 4.1.2 on 2022-11-29 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enrollment_admission_setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('still_accepting', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='for_review_admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='school_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sy', models.CharField(max_length=11, unique=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='shs_strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand_name', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='shs_track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=50, unique=True)),
                ('definition', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='student_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent_home_address', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='student_admission_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('date_of_birth', models.DateField()),
                ('birthplace', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=50)),
                ('elem_name', models.CharField(max_length=50)),
                ('elem_address', models.CharField(max_length=50)),
                ('elem_region', models.CharField(max_length=30)),
                ('elem_year_completed', models.DateField()),
                ('elem_pept_passer', models.BooleanField(default=False)),
                ('elem_pept_date_completion', models.DateField(blank=True, null=True)),
                ('elem_ae_passer', models.BooleanField(default=False)),
                ('elem_ae_date_completion', models.DateField(blank=True, null=True)),
                ('elem_community_learning_center', models.CharField(max_length=50)),
                ('elem_clc_address', models.CharField(max_length=50)),
                ('jhs_name', models.CharField(max_length=50)),
                ('jhs_address', models.CharField(max_length=50)),
                ('jhs_region', models.CharField(max_length=30)),
                ('jhs_year_completed', models.DateField()),
                ('jhs_pept_passer', models.BooleanField(default=False)),
                ('jhs_pept_date_completion', models.DateField(blank=True, null=True)),
                ('jhs_ae_passer', models.BooleanField(default=False)),
                ('jhs_ae_date_completion', models.DateField(blank=True, null=True)),
                ('jhs_community_learning_center', models.CharField(max_length=50)),
                ('jhs_clc_address', models.CharField(max_length=50)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_late', models.BooleanField(default=False)),
                ('is_transferee', models.BooleanField(default=False)),
                ('is_denied', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_created'],
                'get_latest_by': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='student_contact_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellphone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='^(09)([0-9]{9})$')])),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='student_enrollment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=35)),
                ('age', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(regex='([0-9])')])),
                ('is_passed', models.BooleanField(default=False)),
                ('is_denied', models.BooleanField(default=False)),
                ('is_late', models.BooleanField(default=False)),
                ('is_repeater', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='student_profile_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='User_profiles/')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='student_report_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_card', models.ImageField(upload_to='Report_cards/%Y/')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
