# Generated by Django 4.1.2 on 2022-11-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment_admission_setup',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
