# Generated by Django 4.1.2 on 2022-11-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_enrollment_details',
            name='report_card',
            field=models.ImageField(upload_to='Report_cards/<function user_instance at 0x00000225DDC69630>/'),
        ),
    ]
