# Generated by Django 4.1.2 on 2022-11-22 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_report_card',
            name='report_card_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reportcard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_profile_image',
            name='image_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_image', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_enrollment_details',
            name='admission_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_student_enrollment_details', to='adminportal.student_admission_details'),
        ),
        migrations.AddField(
            model_name='student_enrollment_details',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_report_card', to='adminportal.student_report_card'),
        ),
        migrations.AddField(
            model_name='student_enrollment_details',
            name='contact_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cp_number', to='adminportal.student_contact_number'),
        ),
        migrations.AddField(
            model_name='student_enrollment_details',
            name='enrolled_schoolyear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sy_enrolled', to='adminportal.school_year'),
        ),
        migrations.AddField(
            model_name='student_enrollment_details',
            name='home_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_address', to='adminportal.student_address'),
        ),
        migrations.AddField(
            model_name='student_enrollment_details',
            name='profile_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_profile_image', to='adminportal.student_profile_image'),
        ),
        migrations.AddField(
            model_name='student_enrollment_details',
            name='selected_strand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_strand', to='adminportal.shs_strand'),
        ),
        migrations.AddField(
            model_name='student_enrollment_details',
            name='student_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_enrollment_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_contact_number',
            name='contactnum_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_admission_details',
            name='admission_owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_admission_details',
            name='admission_sy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sy_admitted', to='adminportal.school_year'),
        ),
        migrations.AddField(
            model_name='student_admission_details',
            name='first_chosen_strand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_strand', to='adminportal.shs_strand'),
        ),
        migrations.AddField(
            model_name='student_admission_details',
            name='second_chosen_strand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_strand', to='adminportal.shs_strand'),
        ),
        migrations.AddField(
            model_name='student_address',
            name='address_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shs_strand',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_strand', to='adminportal.shs_track'),
        ),
        migrations.AddField(
            model_name='enrollment_admission_setup',
            name='ea_setup_sy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_sy', to='adminportal.school_year'),
        ),
    ]
