# Generated by Django 4.1.2 on 2022-12-01 16:09

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0001_initial'),
    ]

    operations = [
        UnaccentExtension()
    ]
