# Generated by Django 4.1.2 on 2022-11-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_enrollment_details',
            name='full_name',
            field=models.CharField(max_length=60),
        ),
    ]
