# Generated by Django 4.1.2 on 2022-11-16 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminportal', '0002_school_year_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_address',
            name='address_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_contact_number',
            name='contactnum_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_profile_image',
            name='image_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_image', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_report_card',
            name='report_card_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reportcard', to=settings.AUTH_USER_MODEL),
        ),
    ]
