# Generated by Django 4.1.2 on 2022-11-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0002_alter_enrollment_admission_setup_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment_admission_setup',
            name='is_visible',
        ),
    ]
