# Generated by Django 4.1.2 on 2022-11-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0003_student_address_address_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='trys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
