# Generated by Django 4.1.2 on 2023-01-31 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0003_studentdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdocument',
            options={'ordering': ['documentName', '-date_created', '-last_modified']},
        ),
    ]
