# Generated by Django 4.1.2 on 2022-12-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0003_auto_20221207_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_details', models.TextField()),
                ('organizers', models.TextField()),
                ('event_start_date', models.DateField()),
                ('event_date_until', models.DateField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
    ]
