# Generated by Django 4.0.3 on 2022-11-30 08:51

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0003_alter_student_enrollment_details_full_name'),
    ]

    operations = [
        UnaccentExtension()
    ]
