# Generated by Django 4.1.2 on 2022-11-20 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0003_remove_enrollment_admission_setup_is_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_admission_details',
            old_name='is_deleted',
            new_name='is_denied',
        ),
        migrations.CreateModel(
            name='for_review_admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('to_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_review', to='adminportal.student_admission_details')),
            ],
        ),
    ]
