# Generated by Django 4.1.2 on 2023-01-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0004_alter_studentdocument_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='documentName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
