# Generated by Django 4.1.2 on 2022-12-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0004_sample_mods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sample_mods',
        ),
    ]
