# Generated by Django 4.1.2 on 2022-11-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0004_rename_is_deleted_student_admission_details_is_denied_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_enrollment_details',
            old_name='is_deleted',
            new_name='is_denied',
        ),
    ]
