# Generated by Django 4.1.2 on 2022-11-17 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0004_trys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trys',
        ),
    ]
