# Generated by Django 4.1.2 on 2022-11-30 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0004_auto_20221130_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrollment_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('to_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_review', to='adminportal.student_enrollment_details')),
            ],
        ),
    ]
