# Generated by Django 4.1.2 on 2022-11-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shs_strand',
            name='strand_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shs_track',
            name='track_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
