# Generated by Django 4.1.2 on 2023-02-12 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0005_schoolsections_sectionschedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolsections',
            name='assignedStrand',
        ),
        migrations.RemoveField(
            model_name='schoolsections',
            name='assignedSubjects',
        ),
        migrations.RemoveField(
            model_name='schoolsections',
            name='sy',
        ),
        migrations.RemoveField(
            model_name='sectionschedule',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sectionschedule',
            name='subject',
        ),
        migrations.DeleteModel(
            name='curriculum',
        ),
        migrations.DeleteModel(
            name='schoolSections',
        ),
        migrations.DeleteModel(
            name='sectionSchedule',
        ),
    ]
