# Generated by Django 4.1.2 on 2023-02-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0005_alter_studentdocument_documentname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment_review',
            name='to_review',
        ),
        migrations.RemoveField(
            model_name='for_review_admission',
            name='to_review',
        ),
        migrations.RemoveField(
            model_name='student_address',
            name='address_owner',
        ),
        migrations.RemoveField(
            model_name='student_admission_details',
            name='admission_owner',
        ),
        migrations.RemoveField(
            model_name='student_admission_details',
            name='admission_sy',
        ),
        migrations.RemoveField(
            model_name='student_admission_details',
            name='first_chosen_strand',
        ),
        migrations.RemoveField(
            model_name='student_admission_details',
            name='second_chosen_strand',
        ),
        migrations.RemoveField(
            model_name='student_contact_number',
            name='contactnum_owner',
        ),
        migrations.RemoveField(
            model_name='student_enrollment_details',
            name='admission_details',
        ),
        migrations.RemoveField(
            model_name='student_enrollment_details',
            name='card',
        ),
        migrations.RemoveField(
            model_name='student_enrollment_details',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='student_enrollment_details',
            name='enrolled_schoolyear',
        ),
        migrations.RemoveField(
            model_name='student_enrollment_details',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='student_enrollment_details',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='student_enrollment_details',
            name='selected_strand',
        ),
        migrations.RemoveField(
            model_name='student_enrollment_details',
            name='student_user',
        ),
        migrations.RemoveField(
            model_name='student_profile_image',
            name='image_user',
        ),
        migrations.RemoveField(
            model_name='student_report_card',
            name='report_card_owner',
        ),
        migrations.DeleteModel(
            name='enrollment_admission_setup',
        ),
        migrations.DeleteModel(
            name='enrollment_review',
        ),
        migrations.DeleteModel(
            name='for_review_admission',
        ),
        migrations.DeleteModel(
            name='school_year',
        ),
        migrations.DeleteModel(
            name='student_address',
        ),
        migrations.DeleteModel(
            name='student_admission_details',
        ),
        migrations.DeleteModel(
            name='student_contact_number',
        ),
        migrations.DeleteModel(
            name='student_enrollment_details',
        ),
        migrations.DeleteModel(
            name='student_profile_image',
        ),
        migrations.DeleteModel(
            name='student_report_card',
        ),
    ]
