# Generated by Django 4.1.2 on 2022-11-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0005_alter_shs_strand_strand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_admission_details',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student_admission_details',
            name='is_transferee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student_enrollment_details',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student_enrollment_details',
            name='is_repeater',
            field=models.BooleanField(default=False),
        ),
    ]
