# Generated by Django 4.1.2 on 2022-12-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0005_event_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school_events',
            old_name='is_hidden',
            new_name='is_cancelled',
        ),
    ]
