# Generated by Django 4.1.2 on 2022-11-14 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0006_student_admission_details_is_late_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrollment_admission_setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_visible', models.BooleanField(default=False)),
                ('still_accepting', models.BooleanField(default=True)),
                ('ea_setup_sy', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_sy', to='adminportal.school_year')),
            ],
        ),
    ]
