# Generated by Django 4.1.2 on 2023-02-05 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0006_remove_enrollment_review_to_review_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event_img',
        ),
        migrations.DeleteModel(
            name='school_events',
        ),
    ]
