# Generated by Django 4.1.2 on 2023-02-12 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0001_initial'),
        ('adminportal', '0006_remove_schoolsections_assignedstrand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='schoolSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('yearLevel', models.CharField(choices=[('11', 'Grade 11'), ('12', 'Grade 12')], max_length=7)),
                ('allowedPopulation', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('assignedStrand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='section_strand', to='adminportal.shs_strand')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='sectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='section_schedule', to='adminportal.schoolsections')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subject_schedule', to='adminportal.subjects')),
            ],
            options={
                'ordering': ['time_in'],
            },
        ),
        migrations.AddField(
            model_name='schoolsections',
            name='assignedSubjects',
            field=models.ManyToManyField(related_name='section', through='adminportal.sectionSchedule', to='adminportal.subjects'),
        ),
        migrations.AddField(
            model_name='schoolsections',
            name='sy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sy_section', to='registrarportal.schoolyear'),
        ),
        migrations.CreateModel(
            name='curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('g11_firstSem_subjects', models.ManyToManyField(related_name='grade11_firstSem', to='adminportal.subjects')),
                ('g11_secondSem_subjects', models.ManyToManyField(related_name='grade11_secondSem', to='adminportal.subjects')),
                ('g12_firstSem_subjects', models.ManyToManyField(related_name='grade12_firstSem', to='adminportal.subjects')),
                ('g12_secondSem_subjects', models.ManyToManyField(related_name='grade12_secondSem', to='adminportal.subjects')),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='curriculum_strand', to='adminportal.shs_strand')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
    ]
