# Generated by Django 4.1.2 on 2023-02-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0007_delete_event_img_delete_school_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_on', models.DateField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
    ]
