# Generated by Django 4.1.2 on 2023-02-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0007_schoolsections_sectionschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shs_strand',
            name='definition',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shs_strand',
            name='strand_name',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
