# Generated by Django 4.1.2 on 2023-02-05 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0008_school_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school_events',
            options={'base_manager_name': 'objects', 'ordering': ['start_on', 'name']},
        ),
    ]
