# Generated by Django 4.1.2 on 2023-02-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0010_alter_schoolsections_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionschedule',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sectionschedule',
            name='subject',
        ),
        migrations.DeleteModel(
            name='schoolSections',
        ),
        migrations.DeleteModel(
            name='sectionSchedule',
        ),
    ]
