# Generated by Django 4.1.2 on 2023-02-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0011_honoredstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honoredstudents',
            name='gradPic',
            field=models.ImageField(default='graduationPictures/default.jpg', upload_to='graduationPictures/%Y'),
        ),
    ]
