# Generated by Django 4.1.2 on 2023-02-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0001_initial'),
        ('adminportal', '0011_remove_sectionschedule_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='firstSemSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.TimeField(null=True)),
                ('time_out', models.TimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['time_in'],
            },
        ),
        migrations.CreateModel(
            name='schoolSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('yearLevel', models.CharField(choices=[('11', 'Grade 11'), ('12', 'Grade 12')], max_length=7)),
                ('allowedPopulation', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('assignedStrand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='section_strand', to='adminportal.shs_strand')),
                ('first_sem_subjects', models.ManyToManyField(related_name='firstSemSubjects', through='adminportal.firstSemSchedule', to='adminportal.subjects')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='secondSemSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.TimeField(null=True)),
                ('time_out', models.TimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='secondSemSched', to='adminportal.schoolsections')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='secondSemSubjectSchedule', to='adminportal.subjects')),
            ],
            options={
                'ordering': ['time_in'],
            },
        ),
        migrations.AddField(
            model_name='schoolsections',
            name='second_sem_subjects',
            field=models.ManyToManyField(related_name='secondSemSubjects', through='adminportal.secondSemSchedule', to='adminportal.subjects'),
        ),
        migrations.AddField(
            model_name='schoolsections',
            name='sy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sy_section', to='registrarportal.schoolyear'),
        ),
        migrations.AddField(
            model_name='firstsemschedule',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='firstSemSched', to='adminportal.schoolsections'),
        ),
        migrations.AddField(
            model_name='firstsemschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='firstSemSubjectSchedule', to='adminportal.subjects'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolsections',
            unique_together={('sy', 'name')},
        ),
    ]
