# Generated by Django 4.1.2 on 2023-02-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0012_firstsemschedule_schoolsections_secondsemschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondsemschedule',
            name='namo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
