# Generated by Django 4.1.2 on 2023-02-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0012_alter_honoredstudents_gradpic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='honoredStudents',
        ),
    ]
