# Generated by Django 4.1.2 on 2023-02-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0014_honoredstudents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='honoredStudents',
        ),
    ]
