# Generated by Django 4.1.2 on 2023-02-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0015_delete_honoredstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_events',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='school_events',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
