# Generated by Django 4.1.2 on 2023-02-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0016_alter_school_events_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_remove', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['title', '-created_on'],
                'unique_together': {('code', 'title')},
            },
        ),
    ]
