# Generated by Django 4.1.2 on 2023-02-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0017_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
