# Generated by Django 4.1.2 on 2023-02-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0018_alter_subjects_code_alter_subjects_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('g11_1q_subjects', models.ManyToManyField(related_name='grade11_firstQuarter', to='adminportal.subjects')),
                ('g11_2q_subjects', models.ManyToManyField(related_name='grade11_secondQuarter', to='adminportal.subjects')),
                ('g11_3q_subjects', models.ManyToManyField(related_name='grade11_thirdQuarter', to='adminportal.subjects')),
                ('g11_4q_subjects', models.ManyToManyField(related_name='grade11_fourthQuarter', to='adminportal.subjects')),
                ('g12_1q_subjects', models.ManyToManyField(related_name='grade12_firstQuarter', to='adminportal.subjects')),
                ('g12_2q_subjects', models.ManyToManyField(related_name='grade12_secondQuarter', to='adminportal.subjects')),
                ('g12_3q_subjects', models.ManyToManyField(related_name='grade12_thirdQuarter', to='adminportal.subjects')),
                ('g12_4q_subjects', models.ManyToManyField(related_name='grade12_fourthQuarter', to='adminportal.subjects')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
    ]
