# Generated by Django 4.1.2 on 2023-02-12 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0020_remove_curriculum_g11_1q_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='schoolSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('allowedPopulation', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='shs_strand',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='track_strand', to='adminportal.shs_track'),
        ),
        migrations.CreateModel(
            name='sectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_schedule', models.JSONField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='section_schedule', to='adminportal.schoolsections')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subject_schedule', to='adminportal.subjects')),
            ],
        ),
        migrations.AddField(
            model_name='schoolsections',
            name='assignedStrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='section_strand', to='adminportal.shs_strand'),
        ),
        migrations.AddField(
            model_name='schoolsections',
            name='assignedSubjects',
            field=models.ManyToManyField(related_name='section', through='adminportal.sectionSchedule', to='adminportal.subjects'),
        ),
    ]
