# Generated by Django 4.1.2 on 2023-02-03 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'ordering': ['-created_on']},
        ),
    ]
