# Generated by Django 4.1.2 on 2023-02-26 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrarportal', '0001_initial'),
        ('adminportal', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_admission_details',
            name='admission_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='admission_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_admission_details',
            name='admission_sy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sy_admitted', to='registrarportal.schoolyear'),
        ),
        migrations.AddField(
            model_name='student_admission_details',
            name='assigned_curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='with_admission', to='adminportal.curriculum'),
        ),
        migrations.AddField(
            model_name='student_admission_details',
            name='first_chosen_strand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='first_strand', to='adminportal.shs_strand'),
        ),
        migrations.AddField(
            model_name='student_admission_details',
            name='second_chosen_strand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='second_strand', to='adminportal.shs_strand'),
        ),
        migrations.AddField(
            model_name='ph_born',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='softCopy_admissionRequirements_phBorn', to='registrarportal.student_admission_details'),
        ),
        migrations.AddField(
            model_name='foreign_citizen_documents',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='softCopy_admissionRequirements_foreigner', to='registrarportal.student_admission_details'),
        ),
        migrations.AddField(
            model_name='enrollment_admission_setup',
            name='ea_setup_sy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='e_a_setup', to='registrarportal.schoolyear'),
        ),
        migrations.AddField(
            model_name='dual_citizen_documents',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='softCopy_admissionRequirements_dualCitizen', to='registrarportal.student_admission_details'),
        ),
        migrations.AddField(
            model_name='admission_batch',
            name='members',
            field=models.ManyToManyField(related_name='admission_batch_member', to='registrarportal.student_admission_details'),
        ),
        migrations.AddField(
            model_name='admission_batch',
            name='sy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sy_admission_batches', to='registrarportal.schoolyear'),
        ),
    ]
