# Generated by Django 4.1.2 on 2023-02-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_admission_details',
            name='with_enrollment',
            field=models.BooleanField(default=False),
        ),
    ]
