# Generated by Django 4.1.2 on 2023-02-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0002_enrollment_admission_setup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='enrollment_admission_setup',
        ),
    ]
