# Generated by Django 4.1.2 on 2023-03-02 07:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrarportal', '0004_student_enrollment_details_student_report_card_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student_enrollment_details',
            unique_together={('applicant', 'admission', 'enrolled_school_year')},
        ),
    ]
