# Generated by Django 4.1.2 on 2023-03-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0005_alter_student_enrollment_details_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student_enrollment_details',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='student_enrollment_details',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='student_enrollment_details',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='student_enrollment_details',
            name='enrolled_school_year',
        ),
        migrations.RemoveField(
            model_name='student_enrollment_details',
            name='strand',
        ),
        migrations.RemoveField(
            model_name='student_home_address',
            name='home_of',
        ),
        migrations.RemoveField(
            model_name='student_id_picture',
            name='image_from',
        ),
        migrations.RemoveField(
            model_name='student_report_card',
            name='card_from',
        ),
        migrations.DeleteModel(
            name='student_contact_number',
        ),
        migrations.DeleteModel(
            name='student_enrollment_details',
        ),
        migrations.DeleteModel(
            name='student_home_address',
        ),
        migrations.DeleteModel(
            name='student_id_picture',
        ),
        migrations.DeleteModel(
            name='student_report_card',
        ),
    ]
