# Generated by Django 4.1.2 on 2023-02-22 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0005_alter_enrollment_admission_setup_ea_setup_sy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_admission_details',
            name='batch_number',
        ),
        migrations.CreateModel(
            name='admission_batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField()),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='admission_batch_member', to='registrarportal.student_admission_details')),
                ('sy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sy_admission_batches', to='registrarportal.schoolyear')),
            ],
            options={
                'ordering': ['batch_number'],
            },
        ),
    ]
