# Generated by Django 4.1.2 on 2023-02-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0006_remove_student_admission_details_batch_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dual_citizen_documents',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='foreign_citizen_documents',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='ph_born',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='student_admission_details',
            name='admission_owner',
        ),
        migrations.RemoveField(
            model_name='student_admission_details',
            name='admission_sy',
        ),
        migrations.RemoveField(
            model_name='student_admission_details',
            name='assigned_curriculum',
        ),
        migrations.RemoveField(
            model_name='student_admission_details',
            name='first_chosen_strand',
        ),
        migrations.RemoveField(
            model_name='student_admission_details',
            name='second_chosen_strand',
        ),
        migrations.DeleteModel(
            name='admission_batch',
        ),
        migrations.DeleteModel(
            name='dual_citizen_documents',
        ),
        migrations.DeleteModel(
            name='foreign_citizen_documents',
        ),
        migrations.DeleteModel(
            name='ph_born',
        ),
        migrations.DeleteModel(
            name='student_admission_details',
        ),
    ]
