# Generated by Django 4.1.2 on 2023-02-22 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0013_secondsemschedule_namo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrarportal', '0007_remove_dual_citizen_documents_admission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_admission_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('date_of_birth', models.DateField()),
                ('birthplace', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=50)),
                ('elem_name', models.CharField(max_length=50)),
                ('elem_address', models.CharField(max_length=50)),
                ('elem_region', models.CharField(max_length=30)),
                ('elem_year_completed', models.DateField()),
                ('elem_pept_passer', models.BooleanField(default=False)),
                ('elem_pept_date_completion', models.DateField(blank=True, null=True)),
                ('elem_ae_passer', models.BooleanField(default=False)),
                ('elem_ae_date_completion', models.DateField(blank=True, null=True)),
                ('elem_community_learning_center', models.CharField(blank=True, max_length=50, null=True)),
                ('elem_clc_address', models.CharField(blank=True, max_length=50, null=True)),
                ('jhs_name', models.CharField(max_length=50)),
                ('jhs_address', models.CharField(max_length=50)),
                ('jhs_region', models.CharField(max_length=30)),
                ('jhs_year_completed', models.DateField()),
                ('jhs_pept_passer', models.BooleanField(default=False)),
                ('jhs_pept_date_completion', models.DateField(blank=True, null=True)),
                ('jhs_ae_passer', models.BooleanField(default=False)),
                ('jhs_ae_date_completion', models.DateField(blank=True, null=True)),
                ('jhs_community_learning_center', models.CharField(blank=True, max_length=50, null=True)),
                ('jhs_clc_address', models.CharField(blank=True, max_length=50, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('1', 'Philippine Born'), ('2', 'Foreign Citizen'), ('3', 'Dual Citizen')], max_length=1)),
                ('is_denied', models.BooleanField(default=False)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('admission_owner', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='admission_details', to=settings.AUTH_USER_MODEL)),
                ('admission_sy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sy_admitted', to='registrarportal.schoolyear')),
                ('assigned_curriculum', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='with_admission', to='adminportal.curriculum')),
                ('first_chosen_strand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='first_strand', to='adminportal.shs_strand')),
                ('second_chosen_strand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='second_strand', to='adminportal.shs_strand')),
            ],
            options={
                'ordering': ['-admission_sy__id', 'created_on'],
                'get_latest_by': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='ph_born',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_moral', models.ImageField(upload_to='admission/goodMorals/%Y')),
                ('report_card', models.ImageField(upload_to='admission/reportCards/%Y')),
                ('psa', models.ImageField(upload_to='admission/studentPsa/%Y')),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='softCopy_admissionRequirements_phBorn', to='registrarportal.student_admission_details')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='foreign_citizen_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_moral', models.ImageField(upload_to='admission/goodMorals/%Y')),
                ('report_card', models.ImageField(upload_to='admission/reportCards/%Y')),
                ('psa', models.ImageField(upload_to='admission/studentPsa/%Y')),
                ('alien_certificate_of_registration', models.ImageField(upload_to='admission/foreignCitizenDocuments/alienRegistration/%Y')),
                ('study_permit', models.ImageField(upload_to='admission/foreignCitizenDocuments/studyPermit/%Y')),
                ('f137', models.ImageField(upload_to='admission/foreignCitizenDocuments/f137s/%Y')),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='softCopy_admissionRequirements_foreigner', to='registrarportal.student_admission_details')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='dual_citizen_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_moral', models.ImageField(upload_to='admission/goodMorals/%Y')),
                ('report_card', models.ImageField(upload_to='admission/reportCards/%Y')),
                ('psa', models.ImageField(upload_to='admission/studentPsa/%Y')),
                ('dual_citizenship', models.ImageField(upload_to='admission/dualCitizenDocuments/dualCitizenshipCertificates/%Y')),
                ('philippine_passport', models.ImageField(upload_to='admission/dualCitizenDocuments/phPassports/%Y')),
                ('f137', models.ImageField(upload_to='admission/dualCitizenDocuments/f137s/%Y')),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='softCopy_admissionRequirements_dualCitizen', to='registrarportal.student_admission_details')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='admission_batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField()),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='admission_batch_member', to='registrarportal.student_admission_details')),
                ('sy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sy_admission_batches', to='registrarportal.schoolyear')),
            ],
            options={
                'ordering': ['batch_number'],
            },
        ),
    ]
