# Generated by Django 4.1.2 on 2023-02-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0008_student_admission_details_ph_born_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admission_batch',
        ),
    ]
