# Generated by Django 4.1.2 on 2023-02-25 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0013_secondsemschedule_namo'),
        ('registrarportal', '0009_delete_admission_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='admission_batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='admission_batch_member', to='registrarportal.student_admission_details')),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='strand_admission_batch', to='adminportal.shs_strand')),
                ('sy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sy_admission_batches', to='registrarportal.schoolyear')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
