# Generated by Django 4.1.2 on 2023-03-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0009_enrollment_batch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='enrollment_batch',
        ),
    ]
