# Generated by Django 4.1.2 on 2023-03-02 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0004_auto_20230226_1840'),
        ('registrarportal', '0010_delete_enrollment_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrollment_batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='enrollment_batch_member', to='registrarportal.student_enrollment_details')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='section_batch', to='adminportal.schoolsections')),
                ('sy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sy_enrollment_batches', to='registrarportal.schoolyear')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
