# Generated by Django 4.1.2 on 2023-03-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0013_student_admission_details_tokenized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_admission_details',
            name='tokenized',
        ),
    ]
