# Generated by Django 4.1.2 on 2023-03-03 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0014_remove_student_admission_details_tokenized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_contact_number',
            name='cellphone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^(09)([0-9]{9})$')]),
        ),
    ]
