# Generated by Django 4.1.2 on 2023-03-04 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrarportal', '0015_alter_student_contact_number_cellphone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrollment_invitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('invitation_to', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='invitation', to='registrarportal.student_admission_details')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
