# Generated by Django 4.1.2 on 2023-01-31 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentrequest',
            options={'ordering': ['scheduled_date']},
        ),
    ]
