# Generated by Django 4.1.2 on 2023-01-31 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0005_alter_studentdocument_documentname'),
        ('studentportal', '0002_alter_documentrequest_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentrequest',
            unique_together={('document', 'scheduled_date')},
        ),
    ]
