# Generated by Django 4.1.2 on 2023-02-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0003_alter_documentrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='is_reschedByRegistrar',
            field=models.BooleanField(default=False),
        ),
    ]
