# Generated by Django 4.1.2 on 2023-02-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0004_documentrequest_is_reschedbyregistrar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentrequest',
            old_name='is_reschedByRegistrar',
            new_name='is_cancelledByRegistrar',
        ),
    ]
