# Generated by Django 4.1.2 on 2023-02-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0005_rename_is_reschedbyregistrar_documentrequest_is_cancelledbyregistrar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentrequest',
            options={'ordering': ['scheduled_date', 'last_modified']},
        ),
    ]
