# Generated by Django 4.1.2 on 2023-02-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0006_alter_documentrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
